### ISSUE TITLE
TinyCAD3.00.00r4 install

### ISSUE THREAD

**Issue by OziIan3880** [matt123p/TinyCAD#1]
G'day.
Don't know if this is the right way or place to do this.

I'm having serious issues with installing TC 3
Seems like no-one else has problems, or it is still too soon after release.
Don't know if it's just me and/or my computer set-up.
Searched forums and no other similar posts (except one in 2009)

Posted issues on the forum - see https://forum.tinycad.net/index.php?p=/discussion/4023/missing-dlls/p1&new=1

Please let me know if you need extra information etc.

Best regards,
OziIan

**Comment by matt123p** [comment]
Hi Ozilan, Can you try installing the Visual Studio redistributable for me and let me know if that fixes it? https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads Make sure you install the x86 version. Thanks,Matt.  Sent from Mail for Windows 10 From: OziIan3880Sent: 12 December 2019 09:37To: matt123p/TinyCADCc: SubscribedSubject: [matt123p/TinyCAD] TinyCAD3.00.00r4 install (#1) G'day.Don't know if this is the right way or place to do this.I'm having serious issues with installing TC 3Seems like no-one else has problems, or it is still too soon after release.Don't know if it's just me and/or my computer set-up.Searched forums and no other similar posts (except one in 2009)Posted issues on the forum - see https://forum.tinycad.net/index.php?p=/discussion/4023/missing-dlls/p1&new=1Please let me know if you need extra information etc.Best regards,OziIan—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
